/// <reference types="miniprogram-api-typings" />
import test from 'node:test';
import assert from 'node:assert/strict';
import {MiniClient,normalizeServer,ApiError} from '../miniprogram/services/client.ts';
import {RoomConnection} from '../miniprogram/services/connection.ts';
import {handRows,tableView,validReturnCards} from '../miniprogram/utils/presentation.ts';
import {createRoom,addPlayer,getRoomView} from '../server/game.ts';
import {createDeck} from '../shared/cards.ts';
import type {Session,RoomView} from '../shared/types.ts';
function platform(){const storage=new Map<string,unknown>([['gd6.server','http://127.0.0.1:3001']]);const requests:WechatMiniprogram.RequestOption[]=[];let status=200;const session:Session={token:'token',userId:'p1',nickname:'牌友',provider:'guest'};
const wxMock={getStorageSync:(k:string)=>storage.get(k),setStorageSync:(k:string,v:unknown)=>storage.set(k,v),removeStorageSync:(k:string)=>storage.delete(k),getAccountInfoSync:()=>({miniProgram:{envVersion:'develop'}}),login:(o:WechatMiniprogram.LoginOption)=>o.success?.({code:'wx-code',errMsg:'ok'}),request:(o:WechatMiniprogram.RequestOption)=>{requests.push(o);o.success?.({statusCode:status,data:status===200?session:{error:'expired'},header:{},cookies:[],errMsg:'ok'} as unknown as WechatMiniprogram.RequestSuccessCallbackResult);}} as unknown as ConstructorParameters<typeof MiniClient>[0];return {api:new MiniClient(wxMock),requests,storage,setStatus:(s:number)=>status=s};}
test('mini server validation allows development LAN but requires HTTPS in release',()=>{assert.equal(normalizeServer(' http://192.168.1.4:3001/ ',true),'http://192.168.1.4:3001');for(const address of ['http://example.com','https://user:pass@example.com','https://example.com/api','https://example.com:65536'])assert.throws(()=>normalizeServer(address,true));assert.throws(()=>normalizeServer('http://127.0.0.1:3001',false));});
test('mini login credentials and room resume are isolated by server',async()=>{const {api,requests}=platform();await api.login('guest','牌友');assert.equal(requests[0].header?.Authorization,undefined);api.remember('123456');await api.request('/api/stats');assert.equal(requests[1].header?.Authorization,'Bearer token');api.setServer('https://other.example.com');assert.equal(api.session(),null);assert.equal(api.roomId(),'');await assert.rejects(()=>api.request('/api/stats'),ApiError);api.setServer('http://127.0.0.1:3001');assert.equal(api.session()?.userId,'p1');assert.equal(api.roomId(),'123456');});
test('mini WeChat login exchanges wx.login code and clears expired identity',async()=>{const {api,requests,setStatus}=platform();await api.login('wechat','微信牌友');assert.deepEqual(requests[0].data,{code:'wx-code',nickname:'微信牌友'});setStatus(401);await assert.rejects(()=>api.stats(),/expired/);assert.equal(api.session(),null);});
test('mini hands use two rows without mutating source; self is bottom and hidden counts stay hidden',()=>{const state=createRoom('123456','p1','一');for(let i=2;i<=6;i++)addPlayer(state,'p'+i,''+i);state.players[3].hand=createDeck().slice(0,27);state.rules.showRemaining=false;state.status='playing';const room=getRoomView(state,'p4');const before=JSON.stringify(room.hand);const vm=tableView(room,[room.hand[0].id],'rank');assert.deepEqual(vm.rows.map(r=>r.cards.length),[14,13]);assert.equal(vm.seats.find(s=>s.seat===4)?.relative,0);assert.ok(vm.seats.filter(s=>s.seat!==4).every(s=>s.detail.includes('牌数隐藏')));assert.equal(vm.rows.flatMap(r=>r.cards).filter(c=>c.selected).length,1);assert.equal(JSON.stringify(room.hand),before);assert.equal(handRows([], '2',[],'rank').length,0);});
test('mini repayment excludes level and falls back to minimum non-wild card',()=>{const deck=createDeck();const get=(rank:string,suit='spade')=>deck.find(c=>c.rank===rank&&c.suit===suit)!;assert.deepEqual(validReturnCards([get('2'),get('3'),get('9'),get('2','heart')],'2').map(c=>c.rank),['3','9']);assert.deepEqual(validReturnCards([get('J'),get('Q'),get('2','heart')],'2').map(c=>c.rank),['J']);});
test('mini socket authenticates, discards stale callbacks, stops on auth error',()=>{type Fake={open:()=>void;message:(p:unknown)=>void;closed:boolean;sent:string[]};const sockets:Fake[]=[];const states:string[]=[];const rooms:RoomView[]=[];let error='';const socketPlatform={connectSocket:()=>{const f:Fake={open:()=>{},message:()=>{},closed:false,sent:[]};sockets.push(f);return {onOpen:(cb:()=>void)=>f.open=cb,onMessage:(cb:(e:{data:string})=>void)=>f.message=p=>cb({data:JSON.stringify(p)}),onClose:()=>{},onError:()=>{},send:(o:{data:string})=>f.sent.push(o.data),close:()=>f.closed=true};}} as unknown as ConstructorParameters<typeof RoomConnection>[0];const connection=new RoomConnection(socketPlatform,'https://example.com',{token:'secret',userId:'p1',nickname:'一',provider:'guest'},'123456',{room:r=>rooms.push(r),state:s=>states.push(s),error:e=>error=e,left:()=>{}});connection.start();sockets[0].open();assert.equal(JSON.parse(sockets[0].sent[0]).token,'secret');connection.stop();connection.start();sockets[0].message({type:'state',room:{revision:1}});assert.equal(rooms.length,0);sockets[1].message({type:'state',room:{revision:2}});assert.equal(rooms[0].revision,2);sockets[1].message({type:'error',error:'expired'});assert.equal(error,'expired');assert.equal(sockets[1].closed,true);assert.equal(states.at(-1),'offline');connection.stop();});
